services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: php

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    depends_on:
      - database


  database:
    image: mysql:8.4

    container_name: database

    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    volumes:
      - database_data:/var/lib/mysql


  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile

    container_name: node

    working_dir: /app

    volumes:
      - ./frontend:/app

    ports:
      - "5173:5173"

    tty: true


volumes:
  database_data: 
